import { Inter } from "next/font/google";
import "./globals.css";

const InterFont = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weights: ["300", "800"],
});

export const metadata = {
  title: "Saudia Academy",
  description: "Generated by MAD TECH",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${InterFont.className}`}>{children}</body>
    </html>
  );
}
